// TODO(borg286): create build file to compile protobuf into python library, another rule to consume that library in along with the code that consumes the generated server and makes an executable python file/package
//   Then make a docker_build rule to consume that python generated code, the user made code, as well as grpcio and protobuf and tosses it into a docker image.
